//APPLICATION CONSTANTS
export const ACTION_SET_PROTECTED_AUTHENTICATE_DATA = 'ACTION_SET_PROTECTED_AUTHENTICATE_DATA';
export const ACTION_SET_APPLICATION_LOADING = 'ACTION_SET_APPLICATION_LOADING';
export const ACTION_SET_APPLICATION_MESSAGES = 'ACTION_SET_APPLICATION_MESSAGES';
export const ACTION_SET_MENU = 'ACTION_SET_MENU';

export const ACTION_USER_STORE_DATA   = "ACTION_USER_STORE_DATA";
export const ACTION_USER_RESTART_DATA = "ACTION_USER_RESTART_DATA";
export const ACTION_AUTH_SET_SIGNGIN  = "ACTION_AUTH_SET_SIGNGIN";
export const ACTION_AUTH_SET_SIGNOUT  = "ACTION_AUTH_SET_SIGNOUT";
export const ACTION_USER_DELETE_DATA  = "ACTION_USER_DELETE_DATA";